[package]
name = "matrix-multiply"
version = "0.1.0"
edition = "2021"
crate-type = "cdylib"


[dependencies]
candid = "0.10.6"
ic-cdk = "0.16.0"
ic-cdk-macros = "0.9.0"

[profile.release]
lto = true
opt-level = 3
